### ISSUE TITLE
Funcionario Central puede ver el Menú de Movimientos.

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#1]
Los Funcionarios sólo deben ver el Menú de Consultas.
Los Usuarios verán Movimientos y Consultas.
Los Administradores verán Movimientos, Consultas, Catálogos y Usuarios.

Entro como Administrador y veo es mi lista de Usuarios: el 01 es un FC.

![sin titulo0](https://cloud.githubusercontent.com/assets/7526072/15332014/9a918b66-1c29-11e6-8d4e-0390bd4d76dd.png)

Pero cuando entro con sus claves, aparece el menú de Movimientos.

![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15332037/af2f20ba-1c29-11e6-8c77-04d144bb96b3.png)

Corregir, y de paso revisar que un Funcionario Estatal también sólo vea Consultas y específicamente de su Estado.

**Comment by ariaocho888** [comment]
De acuerdo a la tabla de Usuario que generamos en las primeras reuniones los Funcionarios pueden entrar a movimientos pero sólo consultar. 
![image](https://cloud.githubusercontent.com/assets/11401672/15332735/7116127c-1c2c-11e6-9cbe-7d03223ac4cd.png)

No se muestran los botones de guardar para que sea de sólo consulta 
![image](https://cloud.githubusercontent.com/assets/11401672/15332954/46aae020-1c2d-11e6-9d6d-934fc9414ba5.png)

Pregunta @FCabeza , ¿quitamos el menú de Movimientos y que sólo puedan entrar a ver el detalle de las Acciones desde el menú de Consultas?

**Comment by FCabeza** [comment]
Como lo hicieron está bien, así que este issue queda cerrado.
