### ISSUE TITLE
Ordenar lista de Gráficas

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#10]
Primero poner las gráficas que grafican sólo los avances (en orden alfabético) y luego poner las que grafican avances vs metas (también en orden alfabético) .

![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15430504/45cc2836-1e6b-11e6-845f-fc110d8f24e5.png)

**Comment by agsneutron** [comment]
solucionado
