### ISSUE TITLE
Listado Sedesol de Educación no está bajando bien.

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#13]
Este listado de Excel no se baja.

![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15431111/044bc6ac-1e6e-11e6-93bf-be440f1e7f00.png)

**Comment by agsneutron** [comment]
Solucionado

**Comment by FCabeza** [comment]
No lo puedo ver

login: fcabeza
password: passpass

**Comment by agsneutron** [comment]
![2016-05-23_10-36-41](https://cloud.githubusercontent.com/assets/6657837/15476345/17db4180-20d4-11e6-9bcf-01a3a86e40c4.jpg)

**Comment by agsneutron** [comment]
![2016-05-23_10-38-06](https://cloud.githubusercontent.com/assets/6657837/15476359/2a359132-20d4-11e6-9ebb-83fbef34cfcc.jpg)

**Comment by agsneutron** [comment]
generado con tu usuario

**Comment by FCabeza** [comment]
Ya lo hice con mi Usuario y no baja.

También con el Usuario de la encargada del Sistema y tampoco bajó bien (los demás Excsls, si):

logion: Issste006C
pass: JOtANjpo

**Comment by FCabeza** [comment]
Aparentemente todos lo pueden bajar y abrir, menos yo.

Cerrado, entonces.
