### ISSUE TITLE
Inversión (mar-jul) no se está actualizando.

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#14]
La inversión de marzo-julio no se actualiza cuando capturo algún dato para esos meses; en cambio la inversión avance si se actualiza. 

Aquí, por ejemplo abril está en 0 y la inversión marzo-julio está en 0.

![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15484451/aace3062-20ff-11e6-9317-5c28e8e7025c.png)

Sin embargo, si capturo algo en abril la inversión marzo-julio no se modifica; en cambio la inversión avance si se actualiza, pasa de $ 3,047,732 a $ 3,056,602; mientras la otra se mantiene en 0.

![sin titulo2](https://cloud.githubusercontent.com/assets/7526072/15484472/cf9061f4-20ff-11e6-81d0-ac3cfafb0aab.png)

La inversión avance se actualiza automáticamente al presionar el botón "guardar y continuar".
Y también si presiono "guardar y salir", entonces cuando vuelvo a entrar ya está actualizada.

**Comment by ariaocho888** [comment]
Se valida fix de Inversión Mar-Jul

![image](https://cloud.githubusercontent.com/assets/11401672/15492685/9c83dab8-2143-11e6-8fb8-91fcc1b2e62f.png)

se agrega avance en mayo, guardar y continuar y actualiza inv. mar-jul
![image](https://cloud.githubusercontent.com/assets/11401672/15492702/c6ca6864-2143-11e6-968a-67267d624c6a.png)

se agrega avance a Jul   , guardar y salir, al entrar nuevamente se muestra actualizado

**Comment by ariaocho888** [comment]
![Uploading image.png…]()
