### ISSUE TITLE
Gráfica de Pirámide saca número raros.

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#2]
La gráfica de Pirámide me encantó para comparar avances vs. metas.

Pero en la parte de abajo pone número raros (muy grandes).

![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15332542/a2df1af2-1c2b-11e6-96f9-6ad09f8d1593.png)

**Comment by agsneutron** [comment]
Solucionado, mostraba el signo % erróneamente, en realidad es la cantidad de unidades, ya sea de avances o de metas
