### ISSUE TITLE
Reportes Predefinidos->Avances por Municipio tiene un error 500. 

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#3]
![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15332737/7139deaa-1c2c-11e6-8f0a-148803198e37.png)

**Comment by FCabeza** [comment]
Mismo problema en los otros 2 Reportes:
Metas sin Avance.
Avances sin Actividad.

**Comment by agsneutron** [comment]
Listo: corregido
