### ISSUE TITLE
Balance general tiene número extraños.

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#4]
En Reportes Predefinidos obtuve el Balance General y tienen algunos números extraños, aquí los señalo.

![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15333077/d0df7422-1c2d-11e6-95c4-2ecad7a7943d.png)

![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15333166/35c1034c-1c2e-11e6-80e3-fa0bead3e1f3.png)

**Comment by FCabeza** [comment]
En los demás PPT también aparecen esos numerotes.

**Comment by agsneutron** [comment]
Solucionado
