### ISSUE TITLE
Las columnas de los Excels siguen teniendo mal el tamaño.

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#6]
Hacer que todas las columnas sean del mismo tamaño y si los números no lo permitieran entonces que sean cuando menos de tamaño semejante.

![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15333584/d8e18fc8-1c2f-11e6-9d95-f3702161d851.png)

**Comment by agsneutron** [comment]
Solucionado
