### ISSUE TITLE
Cambiar la Cabecera.

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#7]
Esto es para Jess.

Cambiar la Cabecera del Sistema por la que ellos nos enviarán.

En cuanto la tenga te la doy para que lo hagas y entonces cerramos este issue.

**Comment by ariaocho888** [comment]
Cambio de header implementado

![image](https://cloud.githubusercontent.com/assets/11401672/15452195/0f4e27e0-1fac-11e6-9863-58b1154c3f1d.png)
![image](https://cloud.githubusercontent.com/assets/11401672/15452203/2c3736ee-1fac-11e6-8af3-bdd9e7713e2c.png)

**Comment by FCabeza** [comment]
No se cambió en los PPT

**Comment by ariaocho888** [comment]
Se cambia cabecera en los ppt


![Uploading image.png…]()
![Uploading image.png…]()

**Comment by FCabeza** [comment]
Ya quedaron cambiadas también en los PPT, por lo tanto se cierra.
