### ISSUE TITLE
Agregar Inversión mar-jul

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#8]
Agregar un renglón en la pantalla de movimientos.

![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15430296/54928afa-1e6a-11e6-9f5c-4b94525e0972.png)

**Comment by ariaocho888** [comment]
Se implementa Inversión Mar-Jul 
![image](https://cloud.githubusercontent.com/assets/11401672/15452247/8a6ae94e-1fad-11e6-90a6-2abc99558f2d.png)
