### ISSUE TITLE
Mejoras en la Lista de Acciones

### ISSUE THREAD

**Issue by FCabeza** [fpedro23/djangoISSSTE#9]
![sin titulo](https://cloud.githubusercontent.com/assets/7526072/15430380/c0c795a8-1e6a-11e6-8a4a-cbfa50a2daac.png)

**Comment by agsneutron** [comment]
solucionado

**Comment by FCabeza** [comment]
Les faltó poder ordenar por "Inversión Meta".

**Comment by FCabeza** [comment]
Ya quedó terminado.
